Updated cliloc support for new client compression
polserver/UOFiddler pull request #125
Opened 2024-08-25 16:25 UTC by Outkome

<img width="629" alt="image" src="https://github.com/user-attachments/assets/63ce4fbe-8951-4551-bd22-53342912d26c">

Using andreakarasho's decoder: https://github.com/ClassicUO/ClassicUO/pull/1699/files#diff-451b93a3ac3243c38ad96607c57fffb29c960708446a7c799ca0ecb6ae558d8e

2024-08-25 17:00 UTC, kluu1988 commented
Split out decoder so we can use it for future gump support.

Tested on current retail Clinoc.enu and for backwards-compatibility.

2024-08-25 21:06 UTC, DragonSlayer62 commented
I tested this code it works great on newer and older clients,

2024-08-27 12:48 UTC, AsYlum- requested changes
Thank you for your PR. There are some things I'd like to see changed. Please let me know if you are willing to work on that.

2024-08-27 12:48 UTC, AsYlum- commented on Ultima/StringList.cs
> -        /// Initialize <see cref="StringList"/> of Language
Why have you removed documentation comments?

2024-08-27 12:48 UTC, AsYlum- commented on Ultima/StringList.cs
> +                ProcessUncompressedFile(fileData);
You should not assume that if exception happens it is due to different file format. There may be number of reasons for an exception. So proper way would be to add in Settings an option similar to "New Map Size"  that will decide if we use old or new cliloc reader. Then you should create proper instance of the StringList based on that setting. This also means that now we need a try catch to gracefully handle problems when loading files as current approach was very simple and a bit naive.

2024-08-27 12:48 UTC, AsYlum- commented on Ultima/StringList.cs
> +                bin.BaseStream.Seek(6, SeekOrigin.Begin);
This is probably:
```
_header1 = bin.ReadInt32();
_header2 = bin.ReadInt16();
```

so I'm not sure why in this case are you skipping the headers instead of reading them like in the uncompressed case?

2024-08-27 12:48 UTC, AsYlum- commented on Ultima/StringList.cs
> +                        _buffer = new byte[(length + 1023) & ~1023];
If it's already uncompressed then why do we need additional 1023 bytes? I don't really understand this.

2024-08-27 13:01 UTC, AsYlum- commented on Ultima/Decoder.cs
It'd be nice to move Decoder.cs to Helpers folder.

2024-08-27 13:24 UTC, AsYlum- commented on Ultima/StringList.cs
> +                        _buffer = new byte[(length + 1023) & ~1023];
Disregard. This was my mistake.

2024-08-27 13:31 UTC, AsYlum- commented on Ultima/StringList.cs
> +                    ushort length = bin.ReadUInt16();
Looking at both methods `ProcessCompressedFile` and `ProcessUncompressedFile` it seems like the only difference is the `byte[] decompressedData = Decoder.Decompress(compressedData);` call as in both cases we read length as short. So it's probably safe to assume this should be unsigned short and the `ushort length = bin.ReadUInt16();` is correct approach in both cases.

2024-12-04 00:57 UTC, AsYlum- commented
Abandoning this as there was no reaction and there was other submission addressing this issue.

2024-12-04 00:57 UTC, closed without merging