Master
polserver/UOFiddler pull request #79
Opened 2021-02-22 17:22 UTC by Maybacco

Added some "Insert starting from" buttons in the LandTile, Gump and Texture tab. It let's you add multiple files at once.

2021-02-25 13:33 UTC, AsYlum- requested changes
Thank you for the PR. Overall looks good but there are few things to clean up before merging. 

For LandTilesControl and TextureControl we have alternative ones LandTilesAlternativeControl and TextureAlternativeControl can you please add the features there as well? Alternative controls uses new faster TileView control and will be main and only controls soon.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/GumpControl.cs
> +
Please remove redundant empty lines.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/GumpControl.cs
> +
Please remove redundant empty lines.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/GumpControl.cs
> +
Please remove redundant empty lines.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/LandTilesControl.cs
> +
Please remove redundant empty lines.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/LandTilesControl.cs
> +                //item.EnsureVisible();
If this code is not needed then please remove it.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/LandTilesControl.cs
> +
Please remove redundant empty lines.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/LandTilesControl.cs
> +
Please remove redundant empty lines.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/TextureControl.cs
> +            //}
If this code is not needed then please remove it.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/TextureControl.cs
> +
Please remove redundant empty lines.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/TextureControl.cs
> +
Please remove redundant empty lines.

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/TileDataControl.cs
> +        private void setTexturesToolStripMenuItem_Click(object sender, EventArgs e)
Method names should start with capital letter -> SetTexturesToolStripMenuItem_Click

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/TileDataControl.cs
> +        private void textBoxTexID_DoubleClick(object sender, EventArgs e)
Method names should start with capital letter -> TextBoxTexID_DoubleClick

2021-02-25 13:33 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/LandTilesControl.cs
> +        private void toolStripTextBox1_KeyDown(object sender, KeyEventArgs e)
Method names should start with capital letter -> ToolStripTextBox1_KeyDown

2021-03-02 18:19 UTC, Maybacco reviewed
Added the feature in LandTilesAlternative and TextureAlternative controls.

Fixed the blank lines and naming.

Added some comments to describe the utility functions.

Got  something strange on TextureAlternative, why are we doing the & with FFF and not with 3FFF as in LandTiles? Are those two files different in size?

2021-03-02 18:27 UTC, AsYlum- commented
It's probably a bug :) looks like we can assume that there is 1:1 texture landtile ratio and it should be 0x3FFF right now

2021-03-02 18:37 UTC, AsYlum- commented
Would you like to do that update with 0x3FFF or should I take over after merge? :)

2021-03-02 18:44 UTC, AsYlum- commented
I've edited PR title and description to better reflect what is changed.

2021-03-02 19:00 UTC, AsYlum- reviewed
This looks like it may fail.

2021-03-02 19:29 UTC, Maybacco commented
It actually gives a "Index out of bounds" on the matrix. I'll look into it to crash-fix that and i'll submit the fix asap!

2021-03-02 19:42 UTC, Maybacco commented on UoFiddler.Controls/UserControls/TextureAlternativeControl.cs
> +        private bool CheckForIndexes(int baseIndex, int count)
I was also trying with the "Insert at.." menu item and by simply writing 0x4000 the software crashes with a Index out of bound.

I'll try to check the TestTexture function to return a false with a out of bound.

2021-03-02 19:50 UTC, AsYlum- commented on UoFiddler.Controls/UserControls/TextureAlternativeControl.cs
> +        private bool CheckForIndexes(int baseIndex, int count)
It should fail at 0x4000 as last valid index is 0x3FFF. 0x4000 is array size that holds items and it's 0-based so 0-0x3FFF :) In CheckForIndexes() method you probably need update if() to also check if current index is not outside of maximum index.

`if (Textures.TestTexture(i) && i < Textures.GetIdxLength() )`

And similar change probably needs to be done for Gumps, Land Tiles and regular Textures control.

2021-03-02 20:47 UTC, AsYlum- approved these changes

2021-03-02 20:50 UTC, AsYlum- commented
Do you plan to add anything else here? If not then I will merge this and put updated pre-release for further testing.

2021-03-02 21:20 UTC, Maybacco commented
For now i don't think so, i'll probably add the same feature in the Items tab. If you want i can add that in the next days and i'll update on this PR

2021-03-02 21:25 UTC, AsYlum- commented
I think it would be better to create new PR for Items changes. 

One tip: It's better to create new feature branch in your fork based on master than commit to forked master and creating PR out of it. Because when I merge this PR right now and you will try to update your fork you will probably get some issues. Better approach is to keep main branches clean and work on feature branches created out of them :)

And once again thank you for your work.

2021-03-02 21:26 UTC, merged